<a href="https://colab.research.google.com/github/Sebastian4524/Datavisualization/blob/main/Estructuras_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. linear Algebra #


In [20]:
#libraries
import numpy as np

In [21]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [27]:
#colum vector
x = np.array([[1],[2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [30]:
# ROW VECTOR
y = np.array([[4,5,6]])
print(y)
print(y.shape)

[[4 5 6]]
(1, 3)


In [65]:
#Matrix a
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [77]:
#1,3
#give the coordinates
print("the first element of x",x[0])
print("the first element of x",y[0,0])
print("the first element of x",a[0,0])


the first element of x [1]
the first element of x 4
the first element of x 1


In [86]:
#extrac more than 1
print("the first two rows of X",x[0:2])
print("the first two rows of Y",y[0,0:2])
print("the first two rows of a",a[0:2,0:2])

the first two rows of X [[1]
 [2]]
the first two rows of Y [4 5]
the first two rows of a [[1 2]
 [4 5]]


In [88]:
#find a value
## find the psition of the number 5 in a


In [98]:
#1.4

z1= np.zeros(5)
print(z1)

z2 = np.zeros((5,5))
print(z2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [107]:
abcd = np.array([[7,8,9,4,5,6,1,2,3,4,5,6,7,8,4,5,5,6,4,1,2,3,6,5,4]])
print(abcd)
abcd.reshape(5,5)

[[7 8 9 4 5 6 1 2 3 4 5 6 7 8 4 5 5 6 4 1 2 3 6 5 4]]


array([[7, 8, 9, 4, 5],
       [6, 1, 2, 3, 4],
       [5, 6, 7, 8, 4],
       [5, 5, 6, 4, 1],
       [2, 3, 6, 5, 4]])

In [113]:
a34 = np.onces((5,5))
print(a34)

AttributeError: module 'numpy' has no attribute 'onces'

In [ ]:
##1.5 random number


### unifrom distribution [0,1)

In [125]:
np.random.rand()

0.315092375714775

In [132]:
# example - coin toss
if np.random.rand()<0.2:
  print("heads")
else:
  print("tails")


tails
