<a href="https://colab.research.google.com/github/Sebastian4524/Datavisualization/blob/main/Estructuras_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. linear Algebra #


In [1]:
#libraries
import numpy as np

In [2]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [3]:
#colum vector
x = np.array([[1],[2],[3]])
print(x)
print(x.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [4]:
# ROW VECTOR
y = np.array([[4,5,6]])
print(y)
print(y.shape)

[[4 5 6]]
(1, 3)


In [5]:
#Matrix a
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
#1,3
#give the coordinates
print("the first element of x",x[0])
print("the first element of x",y[0,0])
print("the first element of x",a[0,0])


the first element of x [1]
the first element of x 4
the first element of x 1


In [7]:
#extrac more than 1
print("the first two rows of X",x[0:2])
print("the first two rows of Y",y[0,0:2])
print("the first two rows of a",a[0:2,0:2])

the first two rows of X [[1]
 [2]]
the first two rows of Y [4 5]
the first two rows of a [[1 2]
 [4 5]]


In [8]:
#find a value
## find the psition of the number 5 in a


In [9]:
#1.4

z1= np.zeros(5)
print(z1)

z2 = np.zeros((5,5))
print(z2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
abcd = np.array([[7,8,9,4,5,6,1,2,3,4,5,6,7,8,4,5,5,6,4,1,2,3,6,5,4]])
print(abcd)
abcd.reshape(5,5)

[[7 8 9 4 5 6 1 2 3 4 5 6 7 8 4 5 5 6 4 1 2 3 6 5 4]]


array([[7, 8, 9, 4, 5],
       [6, 1, 2, 3, 4],
       [5, 6, 7, 8, 4],
       [5, 5, 6, 4, 1],
       [2, 3, 6, 5, 4]])

In [11]:
a34 = np.onces((5,5))
print(a34)

AttributeError: module 'numpy' has no attribute 'onces'

In [ ]:
##1.5 random number


### unifrom distribution [0,1)

In [ ]:
np.random.rand()

In [75]:
# example - coin toss
if np.random.rand()<0.2:
  print("heads")
else:
  print("tails")


heads


In [34]:
toss1 = np.random.rand()
toss2 = np.random.rand()
toss3 = np.random.rand()

if toss1 <= 0.5 and toss2 <= 0.5 and toss3 <= 0.5:
   print("you win 100k")
elif toss1 > 0.5 and toss2 > 0.5 and toss3 > 0.5:
  print("you lose 100K")
else:
  print("nothing happens")

you win 100k


In [36]:
# if you want matrix
np.random.rand(3,2)

array([[0.70869313, 0.16707938],
       [0.37305178, 0.61390235],
       [0.37246412, 0.36107906]])

In [57]:
# if you want numbers outside (0,1)
np.random.uniform(low = -1, high = 3, size = (3,2))

array([[-0.41047691,  1.18578359],
       [-0.04064162,  2.03762727],
       [ 0.29946113, -0.86547322]])

In [309]:
np.random.randint(low = 0, high = 36 )
abc=np.random.randint(low = 0, high = 36 )

abcd = 8

if abc == abcd:
  print( "Ganaste")
else:
  print("perdiste")



perdiste


In [313]:
np.random.randint(low = 0, high = 36 )
abc=np.random.randint(low = 0, high = 36 )

abc22 = 23

if abc < 12 :
 print("docena baja ganada")
elif abc < 25:
  print("docena media ganada")
else:
  print("docena mayor ganada")

docena mayor ganada


In [327]:
np.random.randint(low = 0, high = 36 )
abc=np.random.randint(low = 0, high = 36 )

abcd = 8

if abc == abcd:
  print( "Ganaste")
else:
  print("perdiste")

if abc < 12 :
 print("docena baja ganada")
elif abc < 25:
  print("docena media ganada")
else:
  print("docena mayor ganada")



perdiste
docena media ganada
